FROM node:6.8.0

WORKDIR /project/

RUN git clone https://jourdanrodrigues:3461731bded51950ffd4919a1073d6c4ca39ebda@github.com/jourdanrodrigues/controk-frontend-web.git . && git checkout v0.0.1
RUN npm install
