FROM python:3.5.2

WORKDIR /project/

RUN git clone https://jourdanrodrigues:3461731bded51950ffd4919a1073d6c4ca39ebda@github.com/jourdanrodrigues/controk-webservice.git . && git checkout v0.0.1
RUN pip install -r requirements
